#!/bin/bash

Consider a student object
<Students>
    <Student>
        <Firstname>prassu</Firstname>
        <DOB>2001-05-08</DOB>
        <Email>prassu@gmail.com</Email>
        <Addresses>
            <PermenentAddress>
                <Flat>105</Flat>
                <City>Hyderabad</City>
            </PermenenAaddress>
                <Flat>105</Flat>
                <City>Hyderabad</City>
            <CurrentAddress>
                <Flat>105</Flat>
                <City>Hyderabad</City>
            </CurrentAddress>
        </Addresses>
    </Student>
</Students>

This is example for XML format - we have students object
Each student have their own data.
In students object, we have student object.
Inside student objects we have objects like Firstname, DOB, Addresses ect..


This is JSON format

{
    "students" : 
    [
        {
            "FirstName" : "prassu",
            "DOB" : "2001-05-08",
            "address": [
                {
                "type":"permennet",
                "Flat": 105,
                "City": "Hyderabad",
                },
                {
                "type": "permennet",
                "Flat": 105,
                "City": "Hyderabad",  
                };
            ],
            "skills" : ["java", "devops", "cloud"]
        },
    ]
}


This is YAML format
YAML is similar to python in indentation. space should be specific.

- name: "prassu"
  dob: 2001-05-08
  mobilenumber: 123456789
  Addresses:
  - flat: 105
    city: Hyderabad
    type: permenent

  - flat: 105
    city: Hyderabad
    type: current

- name: "prassu"
  dob: 2001-05-08
  mobilenumber: 123456789
  Addresses:
  - flat: 105
    city: Hyderabad
    type: permenent

  - flat: 105
    city: Hyderabad
    type: current


In ansible commands won't help much so we need to write playbooks

inventory --> whar are the resources available
Inventory means List of servers here in ansible. like what are the servers ansible can connect to.

inventory.ini
in this file we need to give the group of servers which ansible cannoect with.
example.
To give frontend servers
[frontend]
<IP>

To give backend servers
[backend]
<IP>

To give entire list of servers in a project
[roboshop:children]
[frontend]
[backend]

To give dispatach server 
we can give directly without includinh it any group

To run the inventory file
ansible frontend -i inventory.ini --list-hosts
This command will show you the list of frontend servers which are available in inventory

if we want backend servers 
ansible backend -i inventory.ini --list-hosts

if we want all servers 
ansible all -i inventory.ini --list-hosts

if we want specific group like roboshop servers 
ansible roboshop -i inventory.ini --list-hosts

if we want ungrouped or dispatch servers 
ansible ungrouped -i inventory.ini --list-hosts

To see the servers in a graph view
ansible-inventory -i inventory.ini --graph


Ansible is built in python
To connect with amazon or azure etc.. via ansible

we will write the ansible script in playbooks
once we give input in playbooks, ansible runs inside python and connect to 
the system using  API

Ansible handles YAML format easily.

consider a server in inventory and we are trying to ping that server using playbook

playbook1.yaml
- name: ping your server
  hosts: web
  tasks:
  - name: ping the web server
    ansible.builtin.ping:

Here in the inventory, we add web (similar like frontend) and paste the node1 private Ip address
when this playbook is executed, it will go to inventory and look for web and ping the server in the web

command to run the script
ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 playbook1.yaml

we will get result like
[ ec2-user@ip-172-31-73-89 ~/ansible ]$ ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 playbook1.yaml

PLAY [ping your server] *********************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [172.31.71.229]

TASK [ping the web server] ******************************************************************************
ok: [172.31.71.229]

PLAY RECAP **********************************************************************************************
172.31.71.229              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0 

Here gathering facts means variables. 
Before connecting to the server, ansible will gather all the information about that server
like which distribution, which OS, IP, Network info etc.. That is gathering facts

To print anything, refer playbook2.yaml

To install anything refer playbook3.yaml

Here in playbook3, we use ansible.builtin.package command to install nginx
But ngix is available in RHEL, it looks for yum or dnf for installation
In this case, in gathering facts step, the ansible converts the builtin command into dnf (while installing)
If we run in ubuntu, then it will convert builtin command to app install

so this feature makes the ansible as hetrogenous.
which means same code can run in different platforms


To start the application we have builtin caled service
ansbile builtin service

refer playbook3.yaml

Playbook is a list of tasks that can be executed against any server as part of configuration management


Variables
There are different types of variables
1. play level variables

if we give like in this inventory
[local]
localhost

If we give like this, then the server will be lcoalhost
In this case, we don't have need to give username and password.
refer plabook4.yaml

To run the playbook4.yaml
ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 playbook4.yaml

Here we use lcoal host, so no need to give username and password. 
we can run playbook4 like below also
ansible-playbook -i inventory.ini playbook4.yaml

we can define the variables with command/module called vars
To access the variables we use double flower braces {{ variable_name }}


2. Task level variables
These can be defined in task level, which means it is local tp its task.
if we declare variables as play level variables then those can be accessed glocally in entire playbook
if the variable declared inside the task, it is accessed within that task
refer playbook5.yaml
Here course is accessed in task level and duration is accessed in play level


we can also keep the variables in a seperate file can access them
we need to a new yaml file and define the required variables.
Those can be accessed in another yaml file using command
vars_files:
- <variables_file_name>

vars_files:
- variables.yaml

we can read the end user input using command
vars_prompt:
- name: username
  prompt: please enter your username
  private: false


Here we are reading user data in username varibale.
Private is true means, hide the user input while he is typing 
private is false means, display the user input while he is writing (normally)
refer playbook7.yaml

we can pass the variables info into inventory as well and access them.
Go to inventory and give 
[local:vars]
COURSE=Ansible from inventory

refer playbook8.yaml







