# program -1

# - name: Demo on LOOPS
#   hosts: local
#   connection: local
#   tasks:
#   - name: print names
#     ansible.builtin.debug:
#       msg: "Hello {{ item }}"   # here item is reserved keyword from ansible
#     loop:
#     - janu
#     - prassu
#     - jai


# program-2

- name: Installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip


