- name: task level variable
  hosts: local
  connection: local
  vars:
    COURSE: "AWS DEVOPS"
    DURATION: "4 months"
  tasks:
  - name: print variables
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
     msg: "Course is : {{ COURSE }}, Duration is : {{ DURATION }}"